### ISSUE TITLE
Create Activity Class and implement AddActivity function

### ISSUE THREAD

**Issue by iamsamhhh** [iamsamhhh/TravelPlanningApp#2]
Activity Class should contain:
- [x] Name of Activity
- [x] Description of activity
- [x] Cost of activity
- [x] Date and time of activity

Activity class should contain following function:
- [x] initialize activity: store the data above.
- [x] display activity details: display the data above.

**Comment by aniruddhaadak80** [comment]
Assign me please . I am working on this .

**Comment by iamsamhhh** [comment]
finished by pr #10 and modify by #8 and #12
